config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :members, controllers: {
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    omniauth_callbacks: 'members/omniauth_callbacks',
  }

  resources :charges
  resources :cards, only: [:create]

  resources :member_applications, path: 'apply', only: [:new, :create]

  namespace :admin do
    resources :member_applications, path: 'member-applications', only: [:index] do
      post 'approve'
    end
  end

  resources :doorbot_members, only: [:index]

  # Static pages
  get 'about' => 'static_pages#about'
  get 'membership' => 'static_pages#membership'
  get 'classes' => 'static_pages#classes'
  get 'projects' => 'static_pages#projects'
  get 'location' => 'static_pages#location'
  root to: "static_pages#home"
end

app/models/member_application.rb
#
# A MemberApplication holds information we ask for from perspective members
# not all Members will fill in a MemberApplication.
#

class MemberApplication < ApplicationRecord
  has_paper_trail

  belongs_to :member

  validates :name, presence: true
  validates :email, presence: true # TODO validate format

  def approved?
    member.present?
  end

  def create_stripe_customer?
    stripe_id.nil? && stripe_payment_token.present?
  end

  def create_stripe_customer
    stripe_customer = Stripe::Customer.create(
      email: email,
      description: name,
      source: stripe_payment_token,
    )

    self.stripe_id = stripe_customer.id
  end
end

app/controllers/admin/member_applications_controller.rb
class Admin::MemberApplicationsController < ApplicationController
  before_action :verify_admin_member

  def index
    @member = if params[:approved_member].present?
      Member.find(params[:approved_member])
    else
      nil
    end

    @member_applications = MemberApplication.all.order(created_at: :desc)
  end

  def approve
    ActiveRecord::Base.transaction do
      @member_application = MemberApplication.find(params[:member_application_id])
      @member = Member.create_from_member_application(@member_application)

      @member.save!
      @member_application.update!(member: @member)
    end

    if params[:welcome_email].present?
      # This could be async if we wanted to pay for worker instances
      MemberMailer.welcome_email(@member).deliver_now
    end

    redirect_to admin_member_applications_path(approved_member: @member.id)
  end
end

app/controllers/member_applications_controller.rb
class MemberApplicationsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  after_action :send_member_application_email, only: :create

  def new
    @member_application = MemberApplication.new
  end

  def create
    @member_application = MemberApplication.new(member_application_params)

    if @member_application.create_stripe_customer?
      @member_application.create_stripe_customer
    end

    respond_to do |format|
      format.json do
        if @member_application.save
          render json: {success: true}
        else
          render json: {
            success: false,
            errors: @member_application.errors,
          }, status: 522
        end
      end
      format.html do
        if @member_application.save
          # TODO show success
          redirect_to after_create_path
        else
          render :new
        end
      end
    end
  end

private
  def member_application_params
    params.require(:member_application).permit(:name, :email, :rfid, :stripe_payment_token, :vending_machine_enabled)
  end

  def after_create_path
    root_path
  end

  def send_member_application_email
    if @member_application.valid?
      MemberApplicationMailer.application_submitted(@member_application).deliver_now
    end
  end
end

app/views/admin/member_applications/index.haml
%h2 Membership Applications

- if @member
  .alert.alert-info
    %p <strong>#{ @member.name}</strong> isn't a member yet!
    %ol
      %li
        - if @member.stripe_id.present?
          Payment: Make sure this user has an appropriate #{ link_to 'Stripe subscription', @member.stripe_dashboard_url, target: :blank }
        - else
          Payment: If this member isn't paying by Stripe let the membership person know the amount paid
      %li
        Fob: Add the following line to #{ link_to "doorbot file", Rails.application.secrets.github_membership_file_url, target: :blank }:
        %code= @member.to_csv_line
      %li
        Entry: Show them how to use the door downstairs (and make sure they got the welcome email)
      %li
        Mailing list: Add <code>#{ @member.email }</code> to the #{ link_to 'member mailing list', 'http://lists.site3.ca/admin.cgi/members-site3.ca/members/add' }

- if @member_applications
  %table.table
    %thead
      %tr
        %th Name
        %th Email
        %th RFID
        %th Stripe?
        %th
    %tbody
      - @member_applications.each do |member_application|
        %tr
          %td= member_application.name
          %td= member_application.email
          %td= member_application.rfid
          %td
            - if member_application.stripe_id.present?
              = link_to "Yes", "https://dashboard.stripe.com/customers/#{member_application.stripe_id}"
            - if member_application.stripe_payment_token
              Has payment token
            - else
              No
          %td
            - if member_application.approved?
              = link_to "Approval instructions", admin_member_applications_path(approved_member: member_application.member)
            - else
              = form_for(member_application, url: admin_member_application_approve_path(member_application), html: { method: :post, class: "form-inline"}) do |f|
                = f.submit "Approve", class: 'btn btn-primary'
                %label.checkbox.inline
                  %input{type: :checkbox, checked: :checked, name: :welcome_email}
                  Send welcome email