config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :members, controllers: {
    registrations: 'members/registrations',
    sessions: 'members/sessions',
    omniauth_callbacks: 'members/omniauth_callbacks',
  }

  resources :charges
  resources :cards, only: [:create]

  resources :member_applications, path: 'apply', only: [:new, :create]

  namespace :admin do
    resources :member_applications, path: 'member-applications', only: [:index] do
      post 'approve'
    end
  end

  resources :doorbot_members, only: [:index]

  # Static pages
  get 'about' => 'static_pages#about'
  get 'membership' => 'static_pages#membership'
  get 'classes' => 'static_pages#classes'
  get 'projects' => 'static_pages#projects'
  get 'location' => 'static_pages#location'
  root to: "static_pages#home"
end

app/views/layouts/_flashes.haml
.container
  - if notice
    .alert.alert-info
      %p= notice
  - if alert
    .alert.alert-warning
      %p= alert
- flash.clear

app/views/layouts/_footer.haml
/ footer
#footer
  .container
    .row
      .col-md-4.col-sm-6.hours
        %h3.heading Hours
        %table
          %tr
            %td Monday
            %td 4 &ndash; 11pm
            %td <span>Associates &amp; Core</span>
          %tr
            %td Tuesday
            %td 7 &ndash; 10pm
            %td
              %a.callout{href: "#{classes_path}#women-lgbtq-open-studio"} Women + LGBTQ
          %tr
            %td Thursday
            %td 7 &ndash; late
            %td
              %a.callout{href: "#{classes_path}#open-house"} Public open house
          %tr
            %td Sat &amp; Sun
            %td 12 &ndash; 6pm
            %td
              %span Associates &amp; Core
          %tr.member-hours
            %td(colspan="3")
              %a{href: membership_path} core members get 24/7 access &raquo;
      .col-md-4.col-sm-6
        %a#promo-section{href: "https://www.gofundme.com/vyu8x-site-3-colaboratory-needs-your-help", target: "_blank"}
          .promo-content
            %h3
      .clearfix.visible-sm-block
      .col-md-4.col-sm-12.footer-map
        #footer-map-holder
          #footer-map
        %a{href: location_path} view full map and location &raquo;

    .footer-contact
      = mail_to t("email")
      %a{href: t("urls.twitter"), target: "_blank"}
        = fa_icon "twitter"
        %span.sr-only Twitter
      %a{href: t("urls.facebook"), target: "_blank"}
        = fa_icon "facebook-official"
        %span.sr-only Facebook

    .footer-copyright
      &copy; #{ Date.today.year } Site 3 coLaboratory
      &middot;
      - if member_signed_in?
        = link_to "Settings", edit_member_registration_path
        &middot;
        = button_to "Log out", destroy_member_session_path, method: :delete
      - else
        = link_to "Log in", new_member_session_path

app/views/layouts/_top_nav.haml
#header.navbar.navbar-default
  .container
    .navbar-header
      %a.navbar-brand{href: root_path}
        .header-logo
        %span.title Site 3 coLaboratory
        %span.tagline Art and technology workspace
      %button{type: :button, class: "navbar-toggle collapsed", "data-toggle" => "collapse", "data-target" => "#header-navbar-collapse"}
        %span.sr-only Toggle navigation
        .icon-bar
        .icon-bar
        .icon-bar

    #header-navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "About", about_path
        %li= link_to "Membership", membership_path
        %li= link_to "Events / Classes", classes_path
        %li= link_to "Projects", projects_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title = yield(:title); title.present? ? title : t('site_name') %></title>
  <meta name="viewport" content="initial-scale=1, maximum-scale=1" />
  <link rel="icon" href="/favicon.ico" type="image/x-icon">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="//maps.googleapis.com/maps/api/js?key=AIzaSyB2QaD7xDqoFaBGCtwdjjRuSKIewbBji6c&callback=googleMapsLoad" async defer></script>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_classes %>">
  <div id="pre-footer">
    <div id="background-mask"></div>
    <%= render partial: 'layouts/top_nav' %>
    <%= render partial: 'layouts/flashes' %>
    <div id="main" class="container">
      <%= yield %>
    </div>
  </div>
  <%= render partial: 'layouts/footer' %>
  <script>
      Cufon.replace('h1,h2,h3,h4,h5,h6,#header .nav a, #header .title,.hero-content p', {hover: true})
  </script>
</body>
</html>